export const players = [
  {
    id: '634f03e1a7948355de4fe8cf',
    role: 'attack',
    name: 'Ronaldo Nazario',
  },
  {
    id: '636374e13a7f199aabc795a1',
    role: 'goalkeeper',
    name: 'Messi Lionel',
  },
  {
    id: 3,
    name: 'Neymar Junior',
    role: 'attacker',
    totalPoints: 12,
    matches: 10,
    average: 6,
    goals: 6,
    assist: 6,
    penalty: 9,
  },
  {
    id: 5,
    name: 'Zinedine Zidane',
    role: 'defender',
    totalPoints: 15,
    matches: 10,
    average: 5,
    goals: 5,
    assist: 5,
    penalty: 5,
  },
  {
    id: 6,
    name: 'Luis Suarez',
    role: 'defender',
    totalPoints: 10,
    matches: 10,
    average: 8,
    goals: 6,
    assist: 10,
    penalty: 10,
  },
  {
    id: 7,
    name: 'Cristiano Ronaldo',
    role: 'goalkeeper',
    totalPoints: 14,
    matches: 10,
    average: 7,
    goals: 8,
    assist: 8,
    penalty: 9,
  },
  {
    id: 8,
    name: 'Luka Modric',
    role: 'attacker',
    totalPoints: 12,
    matches: 10,
    average: 6,
    goals: 6,
    assist: 6,
    penalty: 9,
  },
  {
    id: 9,
    name: 'Lionel Messi',
    role: 'attacker',
    totalPoints: 15,
    matches: 10,
    average: 5,
    goals: 5,
    assist: 5,
    penalty: 5,
  },
  {
    id: 10,
    name: 'Robert Lewandowski',
    role: 'defender',
    totalPoints: 10,
    matches: 10,
    average: 8,
    goals: 6,
    assist: 10,
    penalty: 10,
  },
  {
    id: 11,
    name: 'Kylian Mbappe',
    role: 'attacker',
    totalPoints: 14,
    matches: 10,
    average: 7,
    goals: 8,
    assist: 8,
    penalty: 9,
  },
  {
    id: 12,
    name: 'Virgil van Dijk',
    role: 'goalkeeper',
    totalPoints: 12,
    matches: 10,
    average: 6,
    goals: 6,
    assist: 6,
    penalty: 9,
  },
  {
    id: 13,
    name: 'Sadio Mane',
    role: 'defender',
    totalPoints: 15,
    matches: 10,
    average: 5,
    goals: 5,
    assist: 5,
    penalty: 5,
  },
  {
    id: 14,
    name: 'Mohamed Salah',
    role: 'attacker',
    totalPoints: 10,
    matches: 10,
    average: 8,
    goals: 6,
    assist: 10,
    penalty: 10,
  },
  {
    id: 15,
    name: 'Kevin De Bruyne',
    role: 'attacker',
    totalPoints: 14,
    matches: 10,
    average: 7,
    goals: 8,
    assist: 8,
    penalty: 9,
  },
  {
    id: 16,
    name: 'Harry Kane',
    role: 'attacker',
    totalPoints: 12,
    matches: 10,
    average: 6,
    goals: 6,
    assist: 6,
    penalty: 9,
  },
];
