export const goalTypes = [
  { key: 'SHORTHANDED_GOAL', value: 'Shorthanded goal' },
  { key: 'POWER_PLAY_GOAL', value: 'Power play goal' },
  { key: 'GOAL_IN_OVERTIME', value: 'Goal in overtime' },
  { key: 'GOAL_ON_A_PENALTY_SHOT', value: 'Goal on a penalty shot' },
  { key: 'GOAL_INTO_EMPTY_NET', value: 'Goal into empty net' },
];
export const penaltyLengths = [
  { key: '2', value: 2 },
  { key: '2+2', value: 4 },
  { key: '5', value: 5 },
  { key: '5+5', value: 10 },
  { key: '5+OT', value: 5 },
  { key: '10', value: 10 },
  { key: '10+OT', value: 10 },
];
export const penaltyTypes = [
  { key: 'VIOLENT_CONDUCT', value: 'Violent conduct' },
  { key: 'BRAWL', value: 'Brawl' },
  { key: 'BUMPING_INTO_A_GUARDRAIL', value: 'Bumping into a guardrail' },
  { key: 'STABBING_WITH_THE_END_OF_A_STICK', value: 'Stabbing with the end of a stick' },
  { key: 'ASSAULT', value: 'Assault' },
  { key: 'BUMPING_FROM_BEHIND', value: 'Bumping from behind' },
  { key: 'FALLING_UNDER_FOOT', value: 'Falling under foot' },
  { key: 'CROSSBOW', value: 'Crossbow' },
  { key: 'ELBOW_FOUL', value: 'Elbow foul' },
  { key: 'EXCESSIVE_HARDNESS', value: 'Excessive hardness' },
  { key: 'ROUGHNESS', value: 'Roughness' },
  { key: 'HEAD_STRIKE', value: 'Head strike' },
  { key: 'HIGH_STICK', value: 'High stick' },
  { key: 'HOLDING', value: 'Holding' },
  { key: 'STICK_GRIP', value: 'Stick grip' },
  { key: 'HOOKING', value: 'Hooking' },
  { key: 'ILLEGAL_OBSTRUCTION', value: 'Illegal obstruction' },
  { key: 'KICKING', value: 'Kicking' },
  { key: 'KNEE_FOUL', value: 'Knee foul' },
  { key: 'CHOPPING', value: 'Chopping' },
  { key: 'STABBING_WITH_THE_TIP_OF_A_STICK', value: 'Stabbing with the tip of a stick' },
  { key: 'TRIPPING', value: 'Tripping' },
  { key: 'HIT_TO_THE_HEAD_AND_NECK_AREA', value: 'Hit to the head and neck area' },
  { key: 'BODY_PLAY_IN_WOMENS_HOCKEY', value: 'Body play in women\'s hockey' },
  { key: 'UNSPORTSMANLIKE_CONDUCT_OF_PLAYERS', value: 'Unsportsmanlike conduct of players' },
  { key: 'UNSPORTSMANLIKE_CONDUCT_BY_OFFICIALS', value: 'Unsportsmanlike conduct by officials' },
  { key: 'DELAY_OF_GAME', value: 'Delay of game' },
  { key: 'ENDING_AFTER_WHISTLE', value: 'Ending after whistle' },
  { key: 'ILLEGAL_OR_DANGEROUS_EQUIPMENT', value: 'Illegal or dangerous equipment' },
  { key: 'BROKEN_STICK', value: 'Broken stick' },
  { key: 'FALLING_ON_THE_PUCK_BY_A_PLAYER', value: 'Falling on the puck by a player' },
  { key: 'FALLING_ON_THE_PUCK_BY_A_GOALTENDER', value: 'Falling on the puck by a goaltender' },
  { key: 'PLAYING_THE_PUCK_WITH_HANDS_BY_A_PLAYER', value: 'Playing the puck with hands by a player' },
  { key: 'PLAYING_THE_PUCK_WITH_THE_GOALIES_HAND', value: 'Playing the puck with the goalie\'s hand' },
  { key: 'INTERFERENCE_AGAINST_SPECTATORS', value: 'Interference against spectators' },
  { key: 'LEAVING_THE_PENALTY_OR_PLAYERS_BENCH', value: 'Leaving the penalty or player\'s bench' },
  { key: 'UNAUTHORISED_LEAVING_THE_PENALTY_BOX', value: 'Unauthorised leaving the penalty box' },
  { key: 'LEAVING_THE_BENCH_DURING_A_SCRUM', value: 'Leaving the bench during a scrum' },
  { key: 'LEAVING_THE_BENCH_BY_TEAM_OFFICIALS', value: 'Leaving the bench by team officials' },
  {
    key: 'REFUSAL_TO_START_THE_GAME__THE_TEAM_IS_ON_THE_FIELD',
    value: 'Refusal to start the game - the team is on the field',
  },
  {
    key: 'REFUSAL_TO_START_THE_GAME__TEAM_NOT_ON_THE_FIELD',
    value: 'Refusal to start the game - team not on the field',
  },
  { key: 'THROWING_A_STICK_OR_ANY_OBJECT_OFF_THE_FIELD', value: 'Throwing a stick or any object off the field' },
  { key: 'THROWING_A_STICK_OR_ANY_OBJECT_ON_THE_FIELD', value: 'Throwing a stick or any object on the field' },
  { key: 'THROWING_A_CLUB_OR_ANY_OBJECT_ON_A_BREAK', value: 'Throwing a club or any object on a break' },
  { key: 'PREVENTION_OF_BLOODBORNE_INFECTION', value: 'Prevention of blood-borne infection' },
  { key: 'PROTEST_BY_CAPTAIN_AND_ALTERNATE_CAPTAINS', value: 'Protest by captain and alternate captains' },
  { key: 'TOO_MANY_PLAYERS_ON_THE_ICE', value: 'Too many players on the ice' },
  { key: 'VIOLATION_OF_SUBSTITUTION_PROCEDURE', value: 'Violation of substitution procedure' },
  { key: 'FILMED_FALL_OR_ALSO_FILMED_FALL', value: 'Filmed fall (or also filmed fall)' },
  { key: 'GOALIE_BEHIND_THE_CENTER_LINE', value: 'Goalie behind the center line' },
  { key: 'GOALIE_ON_THE_BENCH_DURING_A_STOPPAGE_IN_PLAY', value: 'Goalie on the bench during a stoppage in play' },
  { key: 'GOALIE_OUT_OF_THE_CREASE_DURING_A_SCRAMBLE', value: 'Goalie out of the crease during a scramble' },
  {
    key: 'GOALIE_DROPPING_THE_PUCK_ON_THE_OUTSIDE_OF_THE_NET',
    value: 'Goalie dropping the puck on the outside of the net',
  },
  { key: 'PENALTY_SHOT', value: 'Penalty shot' },
];
