export const goalTypes = [
  { key: 'SHORTHANDED_GOAL', value: 'Shorthanded goal' },
  { key: 'POWER_PLAY_GOAL', value: 'Power play goal' },
  { key: 'GOAL_IN_OVERTIME', value: 'Goal in overtime' },
  { key: 'GOAL_ON_A_PENALTY_SHOT', value: 'Goal on a penalty shot' },
  { key: 'GOAL_INTO_EMPTY_NET', value: 'Goal into empty net' },
];
export const penaltyLengths = [
  { key: '2', value: 2 },
  { key: '2+2', value: 4 },
  { key: '5', value: 5 },
  { key: '5+5', value: 10 },
  { key: '5+OT', value: 5 },
  { key: '10', value: 10 },
  { key: '10+OT', value: 10 },
];
export const penaltyTypes = [
  { key: 'VIOLENT_CONDUCT', value: 'Violent conduct' },
  { key: 'BRAWL', value: 'Brawl' },
  { key: 'BUMPING_INTO_A_GUARDRAIL', value: 'Bumping into a guardrail' },
  { key: 'STABBING_WITH_THE_END_OF_A_STICK', value: 'Stabbing with the end of a stick' },
  { key: 'ASSAULT', value: 'Assault' },
  { key: 'BUMPING_FROM_BEHIND', value: 'Bumping from behind' },
  { key: 'FALLING_UNDER_FOOT', value: 'Falling under foot' },
  { key: 'CROSSBOW', value: 'Crossbow' },
  { key: 'ELBOW_FOUL', value: 'Elbow foul' },
  { key: 'EXCESSIVE_HARDNESS', value: 'Excessive hardness' },
  { key: 'ROUGHNESS', value: 'Roughness' },
  { key: 'HEAD_STRIKE', value: 'Head strike' },
  { key: 'HIGH_STICK', value: 'High stick' },
  { key: 'HOLDING', value: 'Holding' },
  { key: 'STICK_GRIP', value: 'Stick grip' },
  { key: 'HOOKING', value: 'Hooking' },
  { key: 'ILLEGAL_OBSTRUCTION', value: 'Illegal obstruction' },
  { key: 'KICKING', value: 'Kicking' },
  { key: 'KNEE_FOUL', value: 'Knee foul' },
  { key: 'CHOPPING', value: 'Chopping' },
  { key: 'STABBING_WITH_THE_TIP_OF_A_STICK', value: 'Stabbing with the tip of a stick' },
  { key: 'TRIPPING', value: 'Tripping' },
  { key: 'HIT_TO_THE_HEAD_AND_NECK_AREA', value: 'Hit to the head and neck area' },
  { key: 'BODY_PLAY_IN_WOMENS_HOCKEY', value: 'Body play in women\'s hockey' },
  { key: 'UNSPORTSMANLIKE_CONDUCT_OF_PLAYERS', value: 'Unsportsmanlike conduct of players' },
  { key: 'UNSPORTSMANLIKE_CONDUCT_BY_OFFICIALS', value: 'Unsportsmanlike conduct by officials' },
  { key: 'DELAY_OF_GAME', value: 'Delay of game' },
  { key: 'ENDING_AFTER_WHISTLE', value: 'Ending after whistle' },
  { key: 'ILLEGAL_OR_DANGEROUS_EQUIPMENT', value: 'Illegal or dangerous equipment' },
  { key: 'BROKEN_STICK', value: 'Broken stick' },
  { key: 'FALLING_ON_THE_PUCK_BY_A_PLAYER', value: 'Falling on the puck by a player' },
  { key: 'FALLING_ON_THE_PUCK_BY_A_GOALTENDER', value: 'Falling on the puck by a goaltender' },
  { key: 'PLAYING_THE_PUCK_WITH_HANDS_BY_A_PLAYER', value: 'Playing the puck with hands by a player' },
  { key: 'PLAYING_THE_PUCK_WITH_THE_GOALIES_HAND', value: 'Playing the puck with the goalie\'s hand' },
  { key: 'INTERFERENCE_AGAINST_SPECTATORS', value: 'Interference against spectators' },
  { key: 'LEAVING_THE_PENALTY_OR_PLAYERS_BENCH', value: 'Leaving the penalty or player\'s bench' },
  { key: 'UNAUTHORISED_LEAVING_THE_PENALTY_BOX', value: 'Unauthorised leaving the penalty box' },
  { key: 'LEAVING_THE_BENCH_DURING_A_SCRUM', value: 'Leaving the bench during a scrum' },
  { key: 'LEAVING_THE_BENCH_BY_TEAM_OFFICIALS', value: 'Leaving the bench by team officials' },
  {
    key: 'REFUSAL_TO_START_THE_GAME__THE_TEAM_IS_ON_THE_FIELD',
    value: 'Refusal to start the game - the team is on the field',
  },
  {
    key: 'REFUSAL_TO_START_THE_GAME__TEAM_NOT_ON_THE_FIELD',
    value: 'Refusal to start the game - team not on the field',
  },
  { key: 'THROWING_A_STICK_OR_ANY_OBJECT_OFF_THE_FIELD', value: 'Throwing a stick or any object off the field' },
  { key: 'THROWING_A_STICK_OR_ANY_OBJECT_ON_THE_FIELD', value: 'Throwing a stick or any object on the field' },
  { key: 'THROWING_A_CLUB_OR_ANY_OBJECT_ON_A_BREAK', value: 'Throwing a club or any object on a break' },
  { key: 'PREVENTION_OF_BLOODBORNE_INFECTION', value: 'Prevention of blood-borne infection' },
  { key: 'PROTEST_BY_CAPTAIN_AND_ALTERNATE_CAPTAINS', value: 'Protest by captain and alternate captains' },
  { key: 'TOO_MANY_PLAYERS_ON_THE_ICE', value: 'Too many players on the ice' },
  { key: 'VIOLATION_OF_SUBSTITUTION_PROCEDURE', value: 'Violation of substitution procedure' },
  { key: 'FILMED_FALL_OR_ALSO_FILMED_FALL', value: 'Filmed fall (or also filmed fall)' },
  { key: 'GOALIE_BEHIND_THE_CENTER_LINE', value: 'Goalie behind the center line' },
  { key: 'GOALIE_ON_THE_BENCH_DURING_A_STOPPAGE_IN_PLAY', value: 'Goalie on the bench during a stoppage in play' },
  { key: 'GOALIE_OUT_OF_THE_CREASE_DURING_A_SCRAMBLE', value: 'Goalie out of the crease during a scramble' },
  {
    key: 'GOALIE_DROPPING_THE_PUCK_ON_THE_OUTSIDE_OF_THE_NET',
    value: 'Goalie dropping the puck on the outside of the net',
  },
  { key: 'PENALTY_SHOT', value: 'Penalty shot' },
];
export const districts = [
  { value: 'Benešov', key: "CZ0201" },
  { value: 'Beroun', key: "CZ0202" },
  { value: 'Blansko', key: "CZ0641" },
  { value: 'Brno-město', key: "CZ0642" },
  { value: 'Brno-venkov', key: "CZ0643" },
  { value: 'Bruntál', key: "CZ0801" },
  { value: 'Břeclav', key: "CZ0644" },
  { value: 'Cheb', key: "CZ0411" },
  { value: 'Chomutov', key: "CZ0422" },
  { value: 'Chrudim', key: "CZ0531" },
  { value: 'Česká Lípa', key: "CZ0511" },
  { value: 'České Budějovice', key: "CZ0311" },
  { value: 'Český Krumlov', key: "CZ0312" },
  { value: 'Děčín', key: "CZ0421" },
  { value: 'Domažlice', key: "CZ0321" },
  { value: 'Frýdek-Místek', key: "CZ0802" },
  { value: 'Havlíčkův Brod', key: "CZ0631" },
  { value: 'Hlavní město Praha', key: "CZ0100" },
  { value: 'Hodonín', key: "CZ0645" },
  { value: 'Hradec Králové', key: "CZ0521" },
  { value: 'Jablonec nad Nisou', key: "CZ0512" },
  { value: 'Jeseník', key: "CZ0711" },
  { value: 'Jičín', key: "CZ0522" },
  { value: 'Jihlava', key: "CZ0632" },
  { value: 'Jindřichův Hradec', key: "CZ0313" },
  { value: 'Karlovy Vary', key: "CZ0412" },
  { value: 'Karviná', key: "CZ0803" },
  { value: 'Kladno', key: "CZ0203" },
  { value: 'Klatovy', key: "CZ0322" },
  { value: 'Kolín', key: "CZ0204" },
  { value: 'Kroměříž', key: "CZ0721" },
  { value: 'Kutná Hora', key: "CZ0205" },
  { value: 'Liberec', key: "CZ0513" },
  { value: 'Litoměřice', key: "CZ0423" },
  { value: 'Louny', key: "CZ0424" },
  { value: 'Mělník', key: "CZ0206" },
  { value: 'Mladá Boleslav', key: "CZ0207" },
  { value: 'Most', key: "CZ0425" },
  { value: 'Náchod', key: "CZ0523" },
  { value: 'Nový Jičín', key: "CZ0804" },
  { value: 'Nymburk', key: "CZ0208" },
  { value: 'Olomouc', key: "CZ0712" },
  { value: 'Opava', key: "CZ0805" },
  { value: 'Ostrava-město', key: "CZ0806" },
  { value: 'Pardubice', key: "CZ0532" },
  { value: 'Pelhřimov', key: "CZ0633" },
  { value: 'Písek', key: "CZ0314" },
  { value: 'Plzeň-jih', key: "CZ0324" },
  { value: 'Plzeň-město', key: "CZ0323" },
  { value: 'Plzeň-sever', key: "CZ0325" },
  { value: 'Prachatice', key: "CZ0315" },
  { value: 'Praha-východ', key: "CZ0209" },
  { value: 'Praha-západ', key: "CZ020A" },
  { value: 'Prostějov', key: "CZ0713" },
  { value: 'Přerov', key: "CZ0714" },
  { value: 'Příbram', key: "CZ020B" },
  { value: 'Rakovník', key: "CZ020C" },
  { value: 'Rokycany', key: "CZ0326" },
  { value: 'Rychnov nad Kněžnou', key: "CZ0524" },
  { value: 'Semily', key: "CZ0514" },
  { value: 'Sokolov', key: "CZ0413" },
  { value: 'Strakonice', key: "CZ0316" },
  { value: 'Svitavy', key: "CZ0533" },
  { value: 'Šumperk', key: "CZ0715" },
  { value: 'Tábor', key: "CZ0317" },
  { value: 'Tachov', key: "CZ0327" },
  { value: 'Teplice', key: "CZ0426" },
  { value: 'Trutnov', key: "CZ0525" },
  { value: 'Třebíč', key: "CZ0634" },
  { value: 'Uherské Hradiště', key: "CZ0722" },
  { value: 'Ústí nad Labem', key: "CZ0427" },
  { value: 'Ústí nad Orlicí', key: "CZ0534" },
  { value: 'Praha', key: "CZ0100" },
  { value: 'Vsetín', key: "CZ0723" },
  { value: 'Vyškov', key: "CZ0646" },
  { value: 'Zlín', key: "CZ0724" },
  { value: 'Znojmo', key: "CZ0647" },
  { value: 'Žďár nad Sázavou', key: "CZ0635" },
];
